services:
  - type: web
    name: article-to-audio-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8000
      - key: SUPABASE_URL
        value: https://qslpqxjoupwyclmguniz.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbHBxeGpvdXB3eWNsbWd1bml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTMzMjUsImV4cCI6MjA3MDYyOTMyNX0.dB41u9cSpH4bD_6W-Jx5rZ4D9ud5yaceNJq-7y6QY5A
      - key: EDGE_TTS_VOICE
        value: en-US-BrianNeural
      - key: DEFAULT_STORAGE_MODE
        value: cloud
      - key: AUTO_SYNC
        value: true
      - key: USER_EMAIL
        value: aettefagh@gmail.com
    disk:
      name: audio-storage
      mountPath: /app/output
      sizeGB: 1